services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=postgres
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 30s
      retries: 5
      
  backend:
    build: ./backend
    container_name: web_backend
    restart: always
    ports:
      - '8004:8000'
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: web_frontend
    restart: always
    ports:
      - '5175:5173'
    command: npm run dev
    depends_on:
      - 'backend'

volumes:
  data: